agent:
  image: swarm
  restart: always
  command: join --advertise={{addr}}:{{port}} {{connection_string}}/swarm
{%- if leader %}
manager:
  image: swarm
  restart: always
  ports:
    - 2376:2375
  volumes:
    - {{charm_dir}}/files/tls:/tls
  command: manage {{connection_string}}/swarm --tlsverify --tlscacert=/tls/ca.pem --tlscert=/tls/cert.pem --tlskey=/tls/key.pem
{% endif -%}
