agent:
  image: swarm
  restart: always
  command: join --advertise={{addr}}:{{port}} {{connection_string}}/swarm
{%- if leader %}
manager:
  image: swarm
  restart: always
  ports:
    - 3376:2375
  volumes:
    - /etc/docker:/tls
  command:
    - manage
    - --tlsverify
    - --tlscacert=/tls/ca.pem
    - --tlscert=/tls/server.pem
    - --tlskey=/tls/server-key.pem
    - --strategy
    - spread
    - --advertise
    - {{ addr }}:{{ port }}
    - {{ connection_string }}/swarm

{% endif -%}
